# -*- coding: utf-8 -*-
"""covid19_visulization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P0hzHLG-KYy0PV9C89DiYTxt7bfwM8Sf
"""

#First install packages of bar_chart_race
pip install bar_chart_race

#import bar_chart_race ,pandas,datetime
import bar_chart_race as bcr
import pandas as pd
from datetime import datetime

#Read CSV file from the location
df = pd.read_csv("sample_data/WHO-COVID-19-global-data.csv")

#Create a name of columns with country
columns=['Date','China','India','United States of America','Canada','Nepal','Brazil','Spain','Italy','Denmark','Russian Federation']

#create an empty DataFrame
new_df=pd.DataFrame(columns=columns,index_col='Date')

#Create set of list of dates and convert it to list and then sort them in ascending order
my_dates=list(set(df['Date_reported'].values))
my_dates.sort(key=lambda date: datetime.strptime(date, "%Y-%m-%d"))

#Assign Dates to new DataFrame
new_df['Date']=my_dates
countries=['China','India','United States of America','Canada','Nepal','Brazil','Spain','Italy','Denmark','Russian Federation']

#Function for assigning the cumulative cases in respective country in respective date
def append_column(country):
  df_country=df[df['Country'] == country]
  new_df[country]=df_country['Cumulative_cases'].values

#Running for loop in countries
#It will be change in future since for loop can be replce with other function
for country in countries:
  append_column(country)

#values in New DataFrame
new_df

#Displaying Bar_chart_race
#It has many attributes will be used in future for making it attractive
bcr.bar_chart_race(
    df=new_df[:100]
)

